apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSjZieVNOVUhEUGN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1qVXhORFF6TWpSYUZ3MHpOREEwTWpNeE5EUTRNalJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNxTzNhYmgvUlc0eUhOaVRyb2tKTDROazBndHRrSkdYeFZXUExyeEFOS2R2dkI2SU9jbVY1VDkxajcKUUtQZExrT0VMeEhLWThvY09UYnlWNVFxY0RYaHM2WGVqRWc2Z3hiVUdYemZvMUhQTzZzaDVCdzBwQUdiU1hKOAo0bmE5WERQUVZUUEJQdldxWFY1WSt5c0txaW5Md3YxSGROc2ZEQ3NMVzdHYWFmNWN6N0kvMWhOZGRVVFlJL2ovCjY5d3kvSUllaVYvRnJZSHRYZ0Z4ak5TU3NMMlVDbGtPYUFLSy9SeHBQMUx6V0w0N0RpRE9IblZSM0lsZWc3SGoKSGhsZnluOThxWEc3WGphTy9oZFdZMGxpbk1aakRhWjJDSGtqVHEwOE5mZXEyYVcrdW82Q080TEdKN1I1eWhNWApFdzBGdkwxUXhuWWRlcnhEeG8zRlcvSlFXczk1QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUUGhZTTJRUmVHVnB0ZldEWFpFZUJVUEgwVjVEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQSszN0NaU2h5UApsWWV3Y3cwZTFTcjF3ZGZyU3BuTVZEbWt3cTN5Z3pyMkF4MFd0OGNJZGdra1V1TTQyTjNtcGRVdVZHNTFWRU1lCi9qbU5HOUVOckRqRi9Cbk13cmlIY1FSSW84MS9XT1JacU5aNnlicjJXY1hVNi96ZTFxU2FyVGlDMHQ2M2wrMjgKWWt1ejdRaDJPNXMwYld0b2lVVHdxVTFvZjdWTFIvcjhkWWxTamxIc1pEcU5HUlN2TzRhT3I4UU5BT1FXQ0pIMQo4M1lzSG1ZOWRoRjlHekdVcEh2WnJ0OXNvOUV5eEw2ZkVCZHlFNXlkbE4xOXVoYlBEd2xDODB1dU1ZMDg1cU84Cjd0ekJLaC9GNnZvcFBOYTl5N1FaazlkclFZS3FXb0FnWE1vaUh0SHZaeHREaVYrM3MzaURZTU1Dek5XMmFUNHcKb2Z1NUVWekxXNnhuCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5D795F1CE2F22C3B3BB93E19AA666DF4.gr7.us-east-1.eks.amazonaws.com
  name: eks-host-cluster
contexts:
- context:
    cluster: eks-host-cluster
    namespace: kube-system
    user: eks-host-cluster
  name: eks-host-cluster
current-context: eks-host-cluster
kind: Config
preferences: {}
users:
- name: eks-host-cluster
  user:
    token: k8s-aws-v1.aHR0cHM6Ly9zdHMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vP0FjdGlvbj1HZXRDYWxsZXJJZGVudGl0eSZWZXJzaW9uPTIwMTEtMDYtMTUmWC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBMkpHRUlGSE9OWERYRUVCRCUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGc3RzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMTUwNTQ2WiZYLUFtei1FeHBpcmVzPTkwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QlM0J4LWs4cy1hd3MtaWQmWC1BbXotU2lnbmF0dXJlPWZjMGYyMzQ0MTQxZmU0NzgwYjM1NmVjYzAwMGY1MzY3Nzg3NWU0MWQwNGQ5ZmJiYmEzZmQzZjdkOTYyN2EzNGE
